/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author PEDRO LUIS MARTINEZ
 */
import controlador.PersonaControlador;
import modelo.Persona;
import modelo.Propietario;
import modelo.Veterinario;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;

public class FormPersona extends JFrame {
    private PersonaControlador controlador;
    private JTextField txtNombre, txtIdentificacion, txtExtra;
    private JTextArea areaListado;
    private JComboBox<String> cmbTipo;

    public FormPersona() {
        setTitle("Gestión de Personas");
        setSize(600, 500);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setLayout(new BorderLayout());
        
        this.setLocationRelativeTo(null);

        controlador = new PersonaControlador();
        initUI();
        mostrarListado();
    }

    private void initUI() {
        JPanel panelSuperior = new JPanel(new GridLayout(5, 2, 5, 5));

        txtNombre = new JTextField();
        txtIdentificacion = new JTextField();
        txtExtra = new JTextField();

        cmbTipo = new JComboBox<>(new String[]{"Propietario", "Veterinario"});
        cmbTipo.addActionListener(e -> actualizarEtiquetaExtra());

        panelSuperior.add(new JLabel("Nombre:"));
        panelSuperior.add(txtNombre);
        panelSuperior.add(new JLabel("Identificación:"));
        panelSuperior.add(txtIdentificacion);
        panelSuperior.add(new JLabel("Tipo de persona:"));
        panelSuperior.add(cmbTipo);
        panelSuperior.add(new JLabel("Teléfono / Especialidad:"));
        panelSuperior.add(txtExtra);

        JButton btnAgregar = new JButton("Agregar");
        JButton btnEliminar = new JButton("Eliminar por ID");

        btnAgregar.addActionListener(this::agregarPersona);
        btnEliminar.addActionListener(this::eliminarPersona);

        panelSuperior.add(btnAgregar);
        panelSuperior.add(btnEliminar);

        areaListado = new JTextArea();
        areaListado.setEditable(false);
        JScrollPane scroll = new JScrollPane(areaListado);

        add(panelSuperior, BorderLayout.NORTH);
        add(scroll, BorderLayout.CENTER);
    }

    private void actualizarEtiquetaExtra() {
        String tipo = (String) cmbTipo.getSelectedItem();
        JLabel lblExtra = (JLabel)((JPanel)getContentPane().getComponent(0)).getComponent(6);
        if (tipo.equals("Propietario")) {
            lblExtra.setText("Teléfono:");
        } else {
            lblExtra.setText("Especialidad:");
        }
    }

    private void agregarPersona(ActionEvent e) {
        String nombre = txtNombre.getText().trim();
        String id = txtIdentificacion.getText().trim();
        String extra = txtExtra.getText().trim();
        String tipo = (String) cmbTipo.getSelectedItem();

        // Validación simple
        if (nombre.isEmpty() || id.isEmpty() || extra.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Todos los campos son obligatorios");
            return;
        }

        Persona persona;
        if (tipo.equals("Propietario")) {
            persona = new Propietario(nombre, id, extra);
        } else {
            persona = new Veterinario(nombre, id, extra);
        }

        controlador.agregar(persona);
        limpiarCampos();
        mostrarListado();
    }

    private void eliminarPersona(ActionEvent e) {
        String id = JOptionPane.showInputDialog(this, "Ingrese ID a eliminar:");
        if (id != null && !id.trim().isEmpty()) {
            controlador.eliminarPorIdentificacion(id.trim());
            mostrarListado();
        }
    }

    private void mostrarListado() {
        StringBuilder sb = new StringBuilder("Listado de personas:\n\n");
        for (Persona p : controlador.listar()) {
            sb.append(p).append("\n");
        }
        areaListado.setText(sb.toString());
    }

    private void limpiarCampos() {
        txtNombre.setText("");
        txtIdentificacion.setText("");
        txtExtra.setText("");
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPersona().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
